# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TrazrGen < Formula
  desc "A tool to generate synthetic OpenTelemetry logs, metrics and traces telemetry data."
  homepage "https://github.com/medxops/trazr-gen"
  version "0.2.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/medxops/trazr-gen/releases/download/v0.2.4/trazr-gen_darwin_amd64.tar.gz"
      sha256 "ef40adbd32188b8d205cff1a1cae4a6efe6011c139cf867a90a5e506a45387c7"

      def install
        bin.install "trazr-gen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/medxops/trazr-gen/releases/download/v0.2.4/trazr-gen_darwin_arm64.tar.gz"
      sha256 "eaee061946be9deafd9a9a6d3bf1fe5ac26e365e1cfb609bd1dec0f2e8db17ff"

      def install
        bin.install "trazr-gen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/medxops/trazr-gen/releases/download/v0.2.4/trazr-gen_linux_amd64.tar.gz"
        sha256 "8083678d47ab99100dcb117d887360a11db21f43f71c31377d35b039767b3c71"

        def install
          bin.install "trazr-gen"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/medxops/trazr-gen/releases/download/v0.2.4/trazr-gen_linux_arm64.tar.gz"
        sha256 "f9ee7ff49d6e900b54da570fc42efff0a72cca9053d311dca1b5dc061d9febd1"

        def install
          bin.install "trazr-gen"
        end
      end
    end
  end

  test do
    system "#{bin}/trazr-gen -v"
  end
end
