# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TrazrGen < Formula
  desc "A tool to generate synthetic OpenTelemetry logs, metrics and traces telemetry data."
  homepage "https://github.com/medxops/trazr-gen"
  version "0.1.87"

  on_macos do
    url "https://github.com/medxops/trazr-gen/releases/download/v0.1.87/trazr-gen_darwin_amd64.tar.gz"
    sha256 "3cc9cf5ac01e467d840c5a50d16302cd3b4f4ac41e9a0893d989380706ea02d8"

    def install
      bin.install "trazr-gen"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the TrazrGen
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/medxops/trazr-gen/releases/download/v0.1.87/trazr-gen_linux_amd64.tar.gz"
        sha256 "0b4b9edfd2ab16e19fdcf67da89488640346a54ce0abc66fc1f69d04fb305610"

        def install
          bin.install "trazr-gen"
        end
      end
    end
  end

  test do
    system "#{bin}/trazr-gen -v"
  end
end
